const ROLE = { ADMIN: 100, CADMIN: 101, USER: 102 }
const EVENTTYPE = { HACKATHON: 1, SEMINAR: 2, WORKSHOP: 3, CONFERENCE: 4 }
const EVENTNAME = {
  1: 'HACKATHON',
  2: 'SEMINAR',
  3: 'WORKSHOP',
  4: 'CONFERENCE',
}
module.exports = { ROLE, EVENTTYPE, EVENTNAME }
